function sr_summary = sr_ratList()

% for rats 53 and 54, triggering was wrong, so we need to figure out just
% how many "good" recordings we have and whether we can use these data

sr_summary.ratID = [38,39,40,41,42,43,44,48,49,53,54,55];

sr_summary.localizers_present = [false,false,false,false,true,false,true,true,true,true,true,false];

sr_summary.camera_distance = [6,6,6,6,8,6,8,8,8,8,8,6];

sr_summary.pawPref = {'left',...
                      'right',...
                      'right',...
                      'right',...
                      'right',...
                      'left',...
                      'right',...
                      'left',...
                      'right',...
                      'left',...
                      'left',...
                      'left'};