function sessionTable_out = cleanUpSessionTable(sessionTable_in)
%
% make sure all numeric data are entered as numbers and not strings/cells.
% Also turn appropriate cell arrays into categorical data

numericFields = {'ratID',...
                 'totalSessions',...
                 'session_in_block',...
                 'laserProbability',...
                 'frameRate',...
                 'preTriggerFrames',...
                 'postTriggerFrames'};
    
categoricalFields = {'trainingStage',...
                     'laserStim',...
                     'laserTrialSetting',...
                     'experimenter',...
                     'laserOnTiming',...
                     'laserOffTiming',...
                     'ratID'};
                 
sessionTable_out = sessionTable_in;

for iField = 1 : length(numericFields)
    
    if iscell(sessionTable_in.(numericFields{iField}))
        
        sessionTable_out.(numericFields{iField}) = ...
            cells_to_array(sessionTable_in.(numericFields{iField}));
        
    end
    
end

for iField = 1 : length(categoricalFields)
            
        sessionTable_out.(categoricalFields{iField}) = ...
            categorical(sessionTable_in.(categoricalFields{iField}));

end