function reachData = initializeReachDataStruct()

reachData.reachEnds = [];
reachData.graspEnds = [];
reachData.reachStarts = [];
reachData.graspStarts = [];
reachData.pdEndPoints = [];
reachData.slotBreachFrame = [];
reachData.firstDigitKinematicsFrame = [];
reachData.pd_trajectory = {};
reachData.pd_pathlength = {};
reachData.segmented_pd_trajectory = {};
reachData.pd_v = {};
reachData.max_pd_v = [];
reachData.dig_trajectory = {};
reachData.dig_pathlength = {};
reachData.segmented_dig_trajectory = {};
reachData.dig2_v = {};
reachData.max_dig2_v = [];
reachData.dig_endPoints = [];
reachData.orientation = {};
reachData.grasp_orientation = {};
reachData.aperture = {};
reachData.grasp_aperture = {};
reachData.trialScores = [];
reachData.ratIDnum = [];
reachData.sessionDate = datetime();
reachData.trialNumbers = [];
reachData.slot_z_wrt_pellet = [];
reachData.flexion = {};
reachData.flexion_grasp = {};

reachData.post_reach_aperture = [];
reachData.post_reach_orientation = [];