function tracks = initializeTracks_20151119()
    % create an empty array of tracks
    tracks = struct(...
        'id', {}, ...
        'bbox', {}, ...
        'color', {}, ...
        'visiblemask1', {}, ...
        'visiblemask2', {}, ...
        'visiblemask3', {}, ...
        'fullmask1', {}, ...
        'fullmask2', {}, ...
        'fullmask3', {}, ...
        'prev_vismask1', {}, ...
        'prev_vismask2', {}, ...
        'prev_vismask3', {}, ...
        'prev_fullmask1', {}, ...
        'prev_fullmask2', {}, ...
        'prev_fullmask3', {}, ...
        'meanHSV', {}, ...
        'stdHSV', {}, ...
        'markers3D', {}, ...
        'prev_markers3D', {}, ...
        'currentDigitMarkers', {}, ...
        'previousDigitMarkers', {}, ...
        'age', {}, ...
        'isvisible', {}, ...
        'markersCalculated', {}, ...
        'totalVisibleCount', {}, ...
        'consecutiveInvisibleCount', {});
end