function tracks = initializeTracks()
    % create an empty array of tracks
    tracks = struct(...
        'id', {}, ...
        'bbox', {}, ...
        'color', {}, ...
        'digitmask1', {}, ...
        'digitmask2', {}, ...
        'digitmask3', {}, ...
        'prevmask1', {}, ...
        'prevmask2', {}, ...
        'prevmask3', {}, ...
        'meanHSV', {}, ...
        'stdHSV', {}, ...
        'markers3D', {}, ...
        'prev_markers3D', {}, ...
        'currentDigitMarkers', {}, ...
        'previousDigitMarkers', {}, ...
        'age', {}, ...
        'isvisible', {}, ...
        'markersCalculated', {}, ...
        'totalVisibleCount', {}, ...
        'consecutiveInvisibleCount', {});
end