function [T] = read_DLC_csv(fname,varargin)
% function to read in a csv file generated by deepLabCut
% DLC format:
%   row 1: "scorer" followed by a scorer label in each column
%   row 2: "bodyparts" followed by the same label in 3 consecutive columns
%       before switching to a new bodypart label
%   Detailed explanation goes here
numHeaderLines = 3;

T = readtable(fname,'headerlines',numHeaderLines,'readrownames',true);

end

