function [frontPanelMask,intMask,extMask] = findFrontPanel(session_mp, imSize)


% mask of the front panel in both mirror views
leftCorners_x = [session_mp.leftMirror.front_panel_top_front(1),...
                 session_mp.leftMirror.front_panel_top_back(1),...
                 session_mp.leftMirror.front_panel_bot_back(1),...
                 session_mp.leftMirror.front_panel_bot_front(1),...
                 session_mp.leftMirror.front_panel_top_front(1)];
             
leftCorners_y = [session_mp.leftMirror.front_panel_top_front(2),...
                 session_mp.leftMirror.front_panel_top_back(2),...
                 session_mp.leftMirror.front_panel_bot_back(2),...
                 session_mp.leftMirror.front_panel_bot_front(2),...
                 session_mp.leftMirror.front_panel_top_front(2)];
             
rightCorners_x = [session_mp.rightMirror.front_panel_top_front(1),...
                  session_mp.rightMirror.front_panel_top_back(1),...
                  session_mp.rightMirror.front_panel_bot_back(1),...
                  session_mp.rightMirror.front_panel_bot_front(1),...
                  session_mp.rightMirror.front_panel_top_front(1)];
             
rightCorners_y = [session_mp.rightMirror.front_panel_top_front(2),...
                  session_mp.rightMirror.front_panel_top_back(2),...
                  session_mp.rightMirror.front_panel_bot_back(2),...
                  session_mp.rightMirror.front_panel_bot_front(2),...
                  session_mp.rightMirror.front_panel_top_front(2)];
              
frontPanelMask_left = poly2mask(leftCorners_x,leftCorners_y,imSize(1),imSize(2));
frontPanelMask_right = poly2mask(rightCorners_x,rightCorners_y,imSize(1),imSize(2));

frontPanelMask = frontPanelMask_left | frontPanelMask_right;

% mask out the region between the front panels in the mirror views
intCorners_x = [session_mp.leftMirror.front_panel_top_back(1),...
                session_mp.rightMirror.front_panel_top_back(1),...
                session_mp.rightMirror.front_panel_bot_back(1),...
                session_mp.leftMirror.front_panel_bot_back(1),...
                session_mp.leftMirror.front_panel_top_back(1)];
            
intCorners_y = [session_mp.leftMirror.front_panel_top_back(2),...
                session_mp.rightMirror.front_panel_top_back(2),...
                session_mp.rightMirror.front_panel_bot_back(2),...
                session_mp.leftMirror.front_panel_bot_back(2),...
                session_mp.leftMirror.front_panel_top_back(2)];
            
intMask = poly2mask(intCorners_x,intCorners_y,imSize(1),imSize(2));

% mask out the region outside the front panels in the mirror views
left_extCorners_x = [1,...
                     session_mp.leftMirror.front_panel_top_front(1),...
                     session_mp.leftMirror.front_panel_bot_front(1),...
                     1,...
                     1];
                 
left_extCorners_y = [1,...
                     session_mp.leftMirror.front_panel_top_front(2),...
                     session_mp.leftMirror.front_panel_bot_front(2),...
                     imSize(1),...
                     1];
                 
right_extCorners_x = [session_mp.rightMirror.front_panel_top_front(1),...
                      session_mp.rightMirror.front_panel_bot_front(1),...
                      imSize(2),...
                      imSize(2),...
                      session_mp.rightMirror.front_panel_top_front(1)];
                 
right_extCorners_y = [session_mp.rightMirror.front_panel_top_front(2),...
                      session_mp.rightMirror.front_panel_bot_front(2),...
                      imSize(1),...
                      1,...
                      session_mp.rightMirror.front_panel_top_front(2)];
                  
left_extMask = poly2mask(left_extCorners_x,left_extCorners_y,imSize(1),imSize(2));
right_extMask = poly2mask(right_extCorners_x,right_extCorners_y,imSize(1),imSize(2));

extMask = (left_extMask | right_extMask);
                 
                 